apiVersion: v1
kind: Service
metadata:
  name: jee-service
spec:
  type: NodePort
  selector:
    app: jee-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001